server:
  port: 8081

spring:
  application:
    name: order-service-application

  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册